name = "logistic"
uuid = "8ccbb2b4-a9ae-43a7-8afd-c6d144711634"
authors = ["kakinumayuta <kakinuma.y.068@ms.saitama-u.ac.jp>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Revise = "3.8.0"
Test = "1.11.0"
